apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: ingress-nginx
  labels:
    app: sqlite-web
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: sqlite-web
